### ISSUE TITLE
Decays even when set to false

### ISSUE THREAD

**Issue by krisavi** [severedsolo/MonthlyBudgets#5] opened 2019-11-04 12:21 UTC
KSP 1.8.1

I set the decay to be false, but it still seems to decay and a lot. From 126 Reputation it went to 31 Reputation. Tried to set the decay rate to 1 in configs, but behaviour is the same.  

Use It Or Lose It seems to reset to config value not the one in persistent.sfs.

**Comment by severedsolo** [comment] 2019-11-04 14:17
Re use it or lose it, are you definitely using the latest version? That should be fixed in 5.0

That decay is way too much for normal rep decay. What are your settings? And do you have the research budget turned on?

**Comment by severedsolo** [comment] 2019-11-04 18:06
A copy of your persistent file wouldn't hurt either

**Comment by severedsolo** [comment] 2019-12-07 09:58
Closed due to lack of info. If the problem reoccurs open a new issue or ping me in this one and I'll reopen it.

**Closed as completed by severedsolo** 2019-12-07 09:58 UTC
Labels: More Info Needed

**Comment by Gordon-Dry** [comment] 2019-12-07 18:53
Damn, I nearly forgot about this issue - I read this over a month ago.

I use MonthlyBudgets 5.0.0.1 on KSP 1.8.1

Yes, I always wondered why the rep decays when I turned that off.
And just checking the persistent.sfs I find this entry:
```
	SCENARIO
	{
		name = BudgetScenario
		scene = 7, 8, 5
		saveGameVersion = 4.11
		LastBudgetUpdate = 7775999.9999999991
		EmergencyFund = 481178
		EmergencyFundPercent = 10
		EmergencyFundingEnabled = True
		MasterSwitch = True
		HardMode = False
		ContractInterceptor = True
		CoverCosts = False
		StopTimeWarp = True
		DecayEnabled = False
		RepDecay = 10
		Multiplier = 2227
		FriendlyInterval = 30
		AvailableWages = 1000
		AssignedWages = 2000
		VesselCost = 1000
		FirstRun = False
		RnD = 10
		JokeSeen = False
		BuildingCostsEnabled = True
		sphCost = 6000
		missionControlCost = 4000
		astronautComplexCost = 2000
		administrationCost = 4000
		vabCost = 6000
		trackingStationCost = 3000
		rndCost = 7000
		otherFacilityCost = 3000
		LaunchCostsEnabled = True
		LaunchCostsVAB = 1000
		LaunchCostsSPH = 100
		LaunchCosts = 2000
		kerbalDeathPenalty = 15
		vesselDeathPenalty = 10
		upgraded = True
	}
```
I dont't see a reference to useItOrLoseIt there, I only find it inside the
GameData\MonthlyBudgets\PluginData\MonthlyBudgetDefaults.cfg where it is set to "True"

**Comment by severedsolo** [comment] 2019-12-07 21:21
@Gordon-Dry - your RnD figure is set to 10% - that's expected behaviour, RnD decays reputation too.

UseItOrLoseIt is a bit more worrying though, I thought I'd fixed that. I'll open a new issue.
